version: "3.9"

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    container_name: api-gateway
    env_file: .env.docker
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8     # Google DNS
      - 1.1.1.1     # Cloudflare DNS
    depends_on:
      - users
      - learning

  users:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: users
    container_name: users
    env_file: .env.docker
    ports:
      - "3001:3001"
    dns:
      - 8.8.8.8     # Google DNS
      - 1.1.1.1     # Cloudflare DNS

  learning:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: learning
    container_name: learning
    env_file: .env.docker
    ports:
      - "3002:3002"
    dns:
      - 8.8.8.8     # Google DNS
      - 1.1.1.1     # Cloudflare DNS
