export const ErrorMessage = {
  USER_NAME_HAS_BEEN_EXISTED: 'User name has been existed',
  USER_NOT_FOUND: 'User not found',
  INVALID_PASSWORD: 'Invalid password',
  ACCOUNT_HAS_BEEN_LOCKED: 'Account has been locked',
  ACCOUNT_HAS_BEEN_EXPIRED: 'Account has been expired',
  ERROR_WHEN_SAVING_USER: 'Error when saving new user',
  ERROR_WHEN_UPDATING_USER: 'Error when updating user',
  ERROR_WHEN_RETRIEVING_MODEL: 'Error when retrieving model',
  ERROR_WHEN_COUNTING_MODEL: 'Error when counting model',
  MODEL_NOT_FOUND: 'Model not found',
  ERROR_WHEN_CREATING_MODEL: 'Error when creating model',
  ERROR_WHEN_UPDATING_MODEL: 'Error when updating model',
  ERROR_WHEN_REMOVING_MODEL: 'Error when removing model',
  ERROR_WHEN_PROCESSING_REFRESH_TOKEN: 'Error when processing refresh token',
  ACCOUNT_HAS_BEEN_LOGIN: 'Your account has been used in another device',
  LOGOUT_SUCCESSFULLY: 'Logout successfully',
  ERROR_WHEN_LOGOUT: 'Error when logout',
  UNAUTHORIZED: 'Unauthorized',
  LOGIN_FAILED: 'Login failed',
  ERROR_WHEN_GENERATING_TOKEN: 'Error when generating token',
};
